local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Search all file" })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = "Search by character" })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = "Search help" })
vim.keymap.set('n', '<C-p>', builtin.buffers, {})
